### ISSUE TITLE
NoScript Redirect Results in 404

### ISSUE THREAD

**Issue by alexymik** [EFForg/panopticlick#43]
Tested with:
Firefox 76
NoScript 11.0.26

Visiting https://panopticlick.eff.org and running the test with NoScript enabled causes a redirect to:

https://firstpartysimulator.org/tracker-nojs

Which is a 404.

https://github.com/EFForg/panopticlick/blob/cb55726d6047350a9a44964cbb63f0d2398bfcf9/templates/kcarter.html#L65

**Comment by Hainish** [comment]
Fixed in https://github.com/EFForg/panopticlick/commit/7af50fa55ab719f679921f654d3e66be79523f9f
