### ISSUE TITLE
Privacy Badger fails "Do Not Track" test

### ISSUE THREAD

**Issue by ghostwords** [EFForg/panopticlick#49]
Privacy Badger fails the DNT test in Chrome and Firefox. (This isn't new behavior, I think it's been broken for a while.)

**Comment by ghostwords** [comment]
To be clear, Privacy Badger supports EFF's DNT policy, and the test should pass.

**Comment by Hainish** [comment]
This is a new behavior of Privacy Badger, Panopticlick's logic here has not changed.

Disabling local learning has unblocked the Panopticlick pseudo-tracking domains `trackersimulator.org` and `eviltracker.net`.  These domains (which do not have DNT policies behind the `/.well-known` path) must be blocked in order for Panopticlick to detect that a similar domain with the DNT policy present has been unblocked.  The behavior of the DNT policy checkmark is contingent on the non-DNT policy domains being blocked.

**Comment by ghostwords** [comment]
I don't think this has anything to do with disabling local learning. I'll look more into this next week, but I filed this issue before starting work on the local learning PR.

**Comment by ghostwords** [comment]
OK, I see, Privacy Badger broke this test as of the 2020.5.12 update: https://github.com/EFForg/privacybadger/issues/2708#issuecomment-719964400

Let's continue in https://github.com/EFForg/privacybadger/issues/2708

**Comment by ghostwords** [comment]
Ahh, I get the connection to local learning now. While the DNT test was broken by no longer checking for DNT policies until after learning to block the domain, it sounds like disabling local learning by default would have also broken the test.
