### ISSUE TITLE
Not blocking fingerprinting (on Panopticlick.com)?

### ISSUE THREAD

**Issue by dhowe** [EFForg/panopticlick#53]
When I pull and build the current extension code (v 2016.5.24), it fails the panopticlick fingerprinting test. Is this a 'priming' issue? Is there a different way to test this from source?

![screen shot 2016-08-22 at 3 59 49 pm](https://cloud.githubusercontent.com/assets/737638/17869523/ae8dadc6-6881-11e6-95ff-2f7ac18f0e16.jpg)

Most of the entropy comes from:

```
Hash of canvas fingerprint    12.69     6594.2
System Fonts                  16.01     65942.0
```

**Comment by Hainish** [comment]
This shows an accurate result.  Please re-create issue if a bug is present

**Comment by ghostwords** [comment]
While this isn't a bug, this test makes Privacy Badger look bad and confuses Privacy Badger users. What Panopticlick tests for and what Privacy Badger actually does about fingerprinting are misaligned. The test makes it seem the only defense for fingerprinting is trying to blend into the crowd. This is not the case; blocking prevalent fingerprinters outright is a practical and effective defense. This issue should be reopened.

**Comment by Hainish** [comment]
Panopticlick is a project that does not have trackers as the sole adversary in mind.  This is why we carefully worded the last result: "Does your browser protect from fingerprinting?" rather than mentioning trackers.

If Privacy Badger does not protect against fingerprinting, this result is accurate and should be kept.  Users should know what the strengths of Privacy Badger are, and what it does not do.  If Privacy Badger does protect against fingerprinting and not just tracking, let's fix that.

**Comment by ghostwords** [comment]
Privacy Badger protects against fingerprinting by detecting when it (canvas fingerprinting, specifically) happens and learning to block fingerprinter domains. So, yes, Privacy Badger protects against fingerprinting, just not in the way Panopticlick measures it. What am I missing?

**Comment by Hainish** [comment]
Does it only block third parties performing this action?

**Comment by Hainish** [comment]
Fingerprinting is not something that only occurs on third parties.

If a site uses fingerprinting to re-identify a user, even after they have cleared their cookies, this is also a danger to the user.  As I said, third-party trackers are not the only adversary we account for in Panopticlick.

**Comment by ghostwords** [comment]
This is still an ongoing issue. Cover Your Tracks continues to mislead visitors into thinking they need to look for fingerprint randomization extensions. The "Protecting you from fingerprinting?" result misses the forest for the trees.
