### ISSUE TITLE
"Partial protection" in stock Chrome browser

### ISSUE THREAD

**Issue by ghostwords** [EFForg/panopticlick#54]
Running tests in a new, all-defaults Chrome profile reports "partial protection". This seems to be a bug caused by [SameSite](https://www.chromium.org/updates/same-site) cookie changes in Chrome, where now cookies are denied in third-party contexts unless sent over https with `SameSite=None`.

**Comment by Hainish** [comment]
Fixed in https://github.com/EFForg/panopticlick/commit/ff38835a3de507f11c93643b1588e715c6d22a77
